name: Axiom CI/CD

on:
  push:
    branches:
      - dev
      - prod

jobs:
  connect-databricks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Set Databricks credentials (DEV)
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_DEV_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_DEV_TOKEN }}" >> $GITHUB_ENV

      - name: Set Databricks credentials (PROD)
        if: github.ref == 'refs/heads/prod'
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_PROD_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_PROD_TOKEN }}" >> $GITHUB_ENV

      - name: Verify Databricks connection
        run: |
          databricks workspace list /
          
      - name: Deploy notebooks to Databricks
        run: |
          databricks workspace import-dir \
            . \
            /Workspace/Repos/Axiom_Git/Axiom \
            --overwrite
